# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'videos-composer' do
       pod 'TwitterKit'
end

target 'videos-composerTests' do

end

target 'videos-composerUITests' do

end

